import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="flex flex-col h-full">
          <div className="flex-initial">
            <Header></Header>
          </div>
          <div className="flex-auto">{children}</div>

          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
